// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIKbWIuih3F0B7ZnrPZIiBb91YAFwOSIM',
    appId: '1:739294928396:web:8b7ef289dc100a736a1829',
    messagingSenderId: '739294928396',
    projectId: 'project-20251216-7bbf9',
    authDomain: 'project-20251216-7bbf9.firebaseapp.com',
    storageBucket: 'project-20251216-7bbf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKmc_Fr5T9mz62wNYA8zqf6lL1DAW_m8',
    appId: '1:739294928396:android:c3269310a52c3b3d6a1829',
    messagingSenderId: '739294928396',
    projectId: 'project-20251216-7bbf9',
    storageBucket: 'project-20251216-7bbf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe86ZwHvrtX8-FuvKF5v88Qu2R_TgQp7M',
    appId: '1:739294928396:ios:f7f0e7418f3f17586a1829',
    messagingSenderId: '739294928396',
    projectId: 'project-20251216-7bbf9',
    storageBucket: 'project-20251216-7bbf9.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe86ZwHvrtX8-FuvKF5v88Qu2R_TgQp7M',
    appId: '1:739294928396:ios:f7f0e7418f3f17586a1829',
    messagingSenderId: '739294928396',
    projectId: 'project-20251216-7bbf9',
    storageBucket: 'project-20251216-7bbf9.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIKbWIuih3F0B7ZnrPZIiBb91YAFwOSIM',
    appId: '1:739294928396:web:dfbf9ec2b4ddb5526a1829',
    messagingSenderId: '739294928396',
    projectId: 'project-20251216-7bbf9',
    authDomain: 'project-20251216-7bbf9.firebaseapp.com',
    storageBucket: 'project-20251216-7bbf9.firebasestorage.app',
  );
}
